### ISSUE TITLE
20/20 Report Generation

### ISSUE THREAD

**Issue by g2gs** [g2-inc/toolchain#26]
Modify and finalize the 20/20 test results report

**Comment by danielshiplett** [comment]
Have modified the ResultsWorker to pull the Cucumber reports from Jenkins as a ZIP file, extract it all to a Test UUID based report directory on the docs server, and modify the HTML so that it looks cleaner.  Still need to make the report directory base path a configuration option and also to modify the test results view in the UI to point to that path on the docs server.

**Comment by danielshiplett** [comment]
Created the toolchain.docs.path and toolchain.docs.server configuration parameters.  The path value is used in the report generator to drop the results in the correct local path.  The server value isn't used yet.  The docs.nist.dev is hard coded into the UI side for the test results path.
